=== TiJ-code/JTrelloDiscordBot/src/main/resources/config.2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (entry*, userMapping?, events?)>
<!ATTLIST config
    version CDATA #REQUIRED
>

<!ELEMENT entry (#PCDATA)>
<!ATTLIST entry
    name CDATA #REQUIRED
>

<!ELEMENT userMapping (user*)>

<!ELEMENT user EMPTY>
<!ATTLIST user
    discord.user.id CDATA #REQUIRED
    trello.user.id CDATA #REQUIRED
>

<!ELEMENT events (event+)>

<!ELEMENT event (format, format, fields?)>
<!ATTLIST event
    name (CARD_CREATED | CARD_COMMENTED | CARD_MOVED | CARD_ADDED_LABEL | CARD_REMOVED_LABEL | CARD_DESCRIPTION_CHANGED | CARD_TITLE_CHANGED) #REQUIRED>

<!ELEMENT format (#PCDATA)>
<!ATTLIST format
    key (title | body) #REQUIRED>

<!ELEMENT fields (field+)>

<!ELEMENT field (format, format)>

=== TiJ-code/JTrelloDiscordBot/src/main/resources/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE config SYSTEM "config.2.dtd">
<config version="2">
    <entry name="discord.channel.id">YOUR_CHANNEL_ID_HERE</entry>
    <entry name="discord.bot.token">YOUR_BOT_TOKEN_HERE</entry>
    <entry name="port">65000</entry>
    <userMapping>
        <user discord.user.id="DISCORD_ID" trello.user.id="TRELLO_ID"/>
    </userMapping>
    <events>
        <event name="CARD_CREATED">
            <format key="title">📥 New Card Created</format>
            <format key="body">**Card:** {#data.card.name}</format>
            <fields>
                <field>
                    <format key="title">List</format>
                    <format key="body">{#data.card.name}</format>
                </field>
            </fields>
        </event>
        <event name="CARD_COMMENTED">
            <format key="title">💬 New Comment on Card</format>
            <format key="body">**Card:** {#data.card.name}{!N}{!N}**Comment:** {#data.text}</format>
        </event>
        <event name="CARD_MOVED">
            <format key="title">🚚 Card Moved</format>
            <format key="body">**Card:** {#card.name}</format>
            <fields>
                <field>
                    <format key="title">From</format>
                    <format key="body">{#data.listBefore.name}</format>
                </field>
                <field>
                    <format key="title">To</format>
                    <format key="body">{#data.listAfter.name}</format>
                </field>
            </fields>
        </event>
        <event name="CARD_ADDED_LABEL">
            <format key="title">🏷️ Added Label To Card</format>
            <format key="body">**Card:** {#data.card.name}</format>
            <fields>
                <field>
                    <format key="title">Label</format>
                    <format key="body">{#data.label.name}</format>
                </field>
            </fields>
        </event>
        <event name="CARD_REMOVED_LABEL">
            <format key="title">🏷️ Removed Label From Card</format>
            <format key="body">**Card:** {#data.card.name}</format>
            <fields>
                <field>
                    <format key="title">Label</format>
                    <format key="body">{#data.label.name}</format>
                </field>
            </fields>
        </event>
        <event name="CARD_DESCRIPTION_CHANGED">
            <format key="title">📝 Description Updated</format>
            <format key="body">**Card:** {#card.name}</format>
            <fields>
                <field>
                    <format key="title">Before</format>
                    <format key="body">{#data.old.desc}</format>
                </field>
                <field>
                    <format key="title">After</format>
                    <format key="body">{#data.card.desc}</format>
                </field>
            </fields>
        </event>
        <event name="CARD_TITLE_CHANGED">
            <format key="title">✏️ Title Updated</format>
            <format key="body">**Card:** {#data.card.name}</format>
            <fields>
                <field>
                    <format key="title">Before</format>
                    <format key="body">{#data.old.name}</format>
                </field>
                <field>
                    <format key="title">After</format>
                    <format key="body">{#data.card.name}</format>
                </field>
            </fields>
        </event>
    </events>
</config>
